version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /simple-python-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /simple-python-app/docker-credentials/password
    DOCKER_REGISTRY_URL: /simple-python-app/docker-credentials/docker-registry-url

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing Dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running Test cases"
      - echo "Passed all test cases"
      - echo "Building Docker image"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"
  post_build:
    commands:
      - echo "Build is successfull"
artifacts:
  files:
    - '**/*'